#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define TAILLE_BLOC 34
#define NB_BLOCS_LARGEUR 12
#define NB_BLOCS_HAUTEUR 12
#define LARGEUR_FENETRE
#define HAUTEUR_FENETRE

enum{HAUT, BAS, GAUCHE, DROITE};
enum{VIDE, MUR, CAISSE, OBJECTIF, MARIO, CAISSE_OK};

#endif // CONSTANTES_H_INCLUDED
